image: node:10.8

stages:
  - compile
  - build
  - test

cache:
  key: 'default'
  paths:
    - node_modules/

before_script:
  - npm install
  - npm prune

compile:
  stage: compile
  script:
    - npm run build

build:
  stage: build
  script:
    - npm run build

test:
  stage: test
  script:
    - npm run test:cov
