image: node:10.8

stages:
  - compile
  - build
  - test

cache:
  key: 'default'
  paths:
    - node_modules/

# Wird vor jeder stage ausgeführt.
before_script:
  # Nun stellen wir nochmal sicher, dass alle npm-Pakete im Cache vorhanden sind
  - npm install
  # und löschen die überzähligen
  - npm prune

compile:
  stage: compile
  script:
    - npm run build

build:
  stage: build
  script:
    - npm run build

test:
  stage: test
  script:
    - npm run test:cov
